---
# tasks file for common_standalone
- name: Install essentials
  sudo: yes
  apt: pkg={{ item }} state=installed force=yes
  with_items:
    - python-dev
    - python-pip
    - libblas-dev 
    - liblapack-dev 
    - libatlas-base-dev 
    - gfortran
    - build-essential

- name: Install utilities
  sudo: yes
  apt: pkg={{ item }} state=installed force=yes
  with_items:
    - htop

- name: Install pip packages
  sudo: yes
  pip: name={{ item }} state=latest
  with_items:
    - numpy
    - pandas
    - numexpr
    - jupyter